# Generated by Django 4.0.8 on 2023-01-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rank',
            field=models.FloatField(),
        ),
    ]
